// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use proxy URL in production so the app works in India (Jio blocks *.supabase.co).
const PROXY_URL = 'https://supabase-proxy.amanbhogal-work.workers.dev';
const fromEnv = import.meta.env.VITE_SUPABASE_URL;
const isProduction = import.meta.env.PROD;
const isAavisdecor = typeof window !== 'undefined' && /aavisdecor\.com$/i.test(window.location.hostname);
const SUPABASE_URL = (isProduction && isAavisdecor && (!fromEnv || fromEnv.includes('supabase.co')))
  ? PROXY_URL
  : (fromEnv || PROXY_URL);
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});